[package]
name = "epoch"
version = "0.1.0"
edition = "2021"
description = "A tiny CLI to instantly convert between unix timestamps and human-readable dates"
license = "MIT"
authors = ["Animesh Raj <animesh080808@gmail.com>"]
repository = "https://github.com/itsarraj/epoch"
readme = "README.md"
keywords = ["epoch", "timestamp", "date", "time", "cli"]
categories = ["command-line-utilities"]

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
colored = "2"
